# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templog',
            name='recv_timestamp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
